# Generated by Django 3.2.8 on 2021-11-04 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='title',
        ),
    ]
