FROM python:3.9

RUN mkdir /backend

WORKDIR /backend

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1


COPY requirements.txt /backend/


RUN pip install --upgrade pip
RUN pip install -r requirements.txt

EXPOSE 8000

#COPY entrypoint.sh entrypoint.sh
#RUN sed -i 's/\r$//g' /backend/entrypoint.sh
#RUN chmod +x /backend/entrypoint.sh

COPY . /backend/

# run entrypoint.sh
#ENTRYPOINT ["/backend/entrypoint.sh"]
