version: '3.9'

services:

  db:
    restart: always
    image: postgres
    hostname: postgres
    container_name: postgres_blog
#    volumes:
#      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - .env



  backend:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: bash -c "gunicorn django_cache.wsgi --bind 0.0.0.0:8000"
    container_name: backend_blog
    image: backend_image
    volumes:
      - .:/app/
    ports:
      - 8000:8000
#    links:
#      - postgres
    env_file:
      - .env
    depends_on:
      - db


  scheduler:
    restart: always
    build:
      context: .
      dockerfile: SchedulerDockerfile
    volumes:
      - .:/app
    container_name: scheduler_blog
    image: scheduler_image



  frontend:
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: frontend_blog
    image: frontend_image
    depends_on:
      - backend
    volumes:
      - ./frontend/nginx:/etc/nginx/conf.d
    ports:
      - 80:80
