FROM python:3.9

RUN mkdir /backend

WORKDIR /backend

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1


COPY requirements.txt /backend/


RUN pip install --upgrade pip
RUN pip install -r requirements.txt

EXOSE 8000

COPY entrypoint.sh entrypoint.sh
RUN sed -i 's/\r$//g' /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh

COPY . /backend/

# run entrypoint.sh
ENTRYPOINT ["/app/entrypoint.sh"]
