version: '3.9'

services:

  frontend:
    container_name: frontend_blog
    build: ./frontend

    volumes:
      - ./frontend:/app/frontend
    ports:
      - 8080:8080
    environment:
      - CHOKIDAR_USERPOLLING=true

  web:
    container_name: app_blog
    restart: always
    build: .

    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8000

  db:
    container_name: postgres_blog
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django123
      - POSTGRES_DB=DjangoBlog

volumes:
  postgres_data:
